#!/usr/bin/env python3
"""Douglas-Peucker YOLO & Labelme Segmentation Polygon Simplification Utility.

Optimizes segmentation labels generated by SAM 2 or X-AnyLabeling by reducing
excessive vertex density and micro-jagged edges via OpenCV cv2.approxPolyDP.
Supports both .txt (YOLO format) and .json (Labelme / X-AnyLabeling format).

Usage:
    python3 prato-do-dia-ml/scripts/simplify_yolo_labels.py --labels-dir data/processed_640 --epsilon-ratio 0.0025
"""

from __future__ import annotations

import argparse
import json
import logging
import shutil
import unicodedata
from pathlib import Path
from typing import Any

import cv2
import numpy as np

from prato_do_dia_ml.annotations import write_yolo_segmentation_txt
from prato_do_dia_ml.schema import CLASS_ID_TO_NAME, SegmentationMask

# Resolve project root dynamically (prato-do-dia)
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_LABELS_DIR = PROJECT_ROOT / "data" / "processed" / "labels"


def sanitize_label(raw_label: str) -> str:
    """Normalize label string by removing accents, converting to lowercase, and converting spaces/hyphens."""
    normalized = unicodedata.normalize("NFKD", raw_label)
    ascii_str = "".join(c for c in normalized if not unicodedata.combining(c))
    return ascii_str.lower().strip().replace(" ", "_").replace("-", "_")


def build_class_lookup() -> dict[str, int]:
    """Build dynamic lookup dictionary from canonical CLASS_ID_TO_NAME taxonomy."""
    lookup: dict[str, int] = {}
    for cid, name in CLASS_ID_TO_NAME.items():
        sanitized = sanitize_label(name)
        lookup[sanitized] = cid
        lookup[f"{cid}:{sanitized}"] = cid
        lookup[f"{cid}_{sanitized}"] = cid
        lookup[str(cid)] = cid
    return lookup


CLASS_LOOKUP = build_class_lookup()


def resolve_class_id(raw_label: str, filename: str = "") -> int | None:
    """Resolve raw label to canonical class ID [0..15] or log explicit warning and return None."""
    clean = sanitize_label(raw_label)
    if clean in CLASS_LOOKUP:
        return CLASS_LOOKUP[clean]

    # Try parsing prefix if label is formatted as "0: tomate" or "0_tomate"
    parts = clean.split(":") if ":" in clean else clean.split("_")
    prefix = parts[0].strip()
    if prefix.isdigit() and int(prefix) in CLASS_ID_TO_NAME:
        return int(prefix)

    location_str = f" em '{filename}'" if filename else ""
    logging.warning(f"Rótulo não reconhecido '{raw_label}'{location_str}. Ignorando anotação.")
    return None


def convert_labelme_to_yolo_segmentation(json_path: Path, output_dir: Path) -> Path:
    """Convert X-AnyLabeling / Labelme JSON file to normalized YOLO TXT segmentation file."""
    data = json.loads(json_path.read_text(encoding="utf-8"))
    img_w = float(data.get("imageWidth", 640.0))
    img_h = float(data.get("imageHeight", 640.0))
    shapes = data.get("shapes", [])

    masks: list[SegmentationMask] = []
    for shape in shapes:
        raw_label = str(shape.get("label", "")).strip()
        pts = shape.get("points", [])
        if not raw_label or len(pts) < 3:
            continue

        class_id = resolve_class_id(raw_label, filename=json_path.name)
        if class_id is None:
            continue

        polygon_pts: list[tuple[float, float]] = [
            (
                float(np.clip(pt[0] / img_w, 0.0, 1.0)),
                float(np.clip(pt[1] / img_h, 0.0, 1.0)),
            )
            for pt in pts
        ]

        masks.append(
            SegmentationMask(
                class_id=class_id,
                confidence=1.0,
                polygon=tuple(polygon_pts),
            )
        )

    txt_path = output_dir / f"{json_path.stem}.txt"
    return write_yolo_segmentation_txt(masks, txt_path)


def simplify_pts(
    pts: list[list[float]],
    epsilon_ratio: float = 0.0025,
    img_w: float = 640.0,
    img_h: float = 640.0,
) -> tuple[list[list[float]], int, int]:
    """Simplify 2D point list using Douglas-Peucker (cv2.approxPolyDP).

    Returns (simplified_pts, orig_count, simplified_count).
    """
    if len(pts) < 3:
        return pts, len(pts), len(pts)

    pts_pixel = np.array(pts, dtype=np.float32).reshape((-1, 1, 2))
    orig_count = len(pts_pixel)
    perimeter = float(cv2.arcLength(pts_pixel, closed=True))
    epsilon = epsilon_ratio * perimeter

    approx = cv2.approxPolyDP(pts_pixel, epsilon, closed=True)
    simplified = approx.reshape((-1, 2))

    if len(simplified) < 3:
        return pts, orig_count, orig_count

    simp_pts = [[round(float(pt[0]), 2), round(float(pt[1]), 2)] for pt in simplified]
    return simp_pts, orig_count, len(simp_pts)


def simplify_polygon(
    class_id: int,
    coords: list[float],
    epsilon_ratio: float = 0.0025,
    img_w: float = 640.0,
    img_h: float = 640.0,
) -> tuple[int, list[float], int, int]:
    """Simplify a single normalized YOLO polygon using cv2.approxPolyDP."""
    if len(coords) < 6 or len(coords) % 2 != 0:
        return class_id, coords, len(coords) // 2, len(coords) // 2

    pts_pixel = [[coords[i] * img_w, coords[i + 1] * img_h] for i in range(0, len(coords), 2)]
    simp_pts, orig_count, simp_count = simplify_pts(pts_pixel, epsilon_ratio=epsilon_ratio, img_w=img_w, img_h=img_h)

    if simp_count < 3:
        return class_id, coords, orig_count, orig_count

    simplified_coords: list[float] = []
    for pt in simp_pts:
        nx = float(max(0.0, min(1.0, pt[0] / img_w)))
        ny = float(max(0.0, min(1.0, pt[1] / img_h)))
        simplified_coords.extend([nx, ny])

    return class_id, simplified_coords, orig_count, simp_count


def simplify_json_file(
    json_path: Path,
    epsilon_ratio: float = 0.0025,
    backup: bool = True,
    dry_run: bool = False,
) -> tuple[int, int, int]:
    """Simplify shapes inside a Labelme / X-AnyLabeling JSON file."""
    data = json.loads(json_path.read_text(encoding="utf-8"))
    img_w = float(data.get("imageWidth", 640.0))
    img_h = float(data.get("imageHeight", 640.0))
    shapes = data.get("shapes", [])

    if not shapes:
        return 0, 0, 0

    if backup and not dry_run:
        backup_path = json_path.with_suffix(".json.bak")
        shutil.copy2(json_path, backup_path)

    total_polys = 0
    file_orig_v = 0
    file_simp_v = 0

    for shape in shapes:
        pts = shape.get("points", [])
        if len(pts) >= 3:
            simp_pts, orig_cnt, simp_cnt = simplify_pts(pts, epsilon_ratio=epsilon_ratio, img_w=img_w, img_h=img_h)
            shape["points"] = simp_pts
            total_polys += 1
            file_orig_v += orig_cnt
            file_simp_v += simp_cnt

    if not dry_run:
        json_path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")

    return total_polys, file_orig_v, file_simp_v


def simplify_yolo_file(
    file_path: Path,
    epsilon_ratio: float = 0.0025,
) -> tuple[list[str], int, int, int]:
    """Process a single YOLO TXT label file."""
    lines = [line.strip() for line in file_path.read_text(encoding="utf-8").splitlines() if line.strip()]

    output_lines: list[str] = []
    file_orig_vertices = 0
    file_simp_vertices = 0
    file_polygons_count = 0

    for line in lines:
        parts = line.split()
        if len(parts) < 7 or (len(parts) - 1) % 2 != 0:
            continue

        try:
            class_id = int(parts[0])
            coords = [float(v) for v in parts[1:]]

            cid, simp_coords, orig_cnt, simp_cnt = simplify_polygon(class_id, coords, epsilon_ratio=epsilon_ratio)

            coords_str = " ".join(f"{c:.6f}" for c in simp_coords)
            output_lines.append(f"{cid} {coords_str}")

            file_orig_vertices += orig_cnt
            file_simp_vertices += simp_cnt
            file_polygons_count += 1
        except ValueError:
            continue

    return output_lines, file_polygons_count, file_orig_vertices, file_simp_vertices


def process_directory(
    labels_dir: Path,
    epsilon_ratio: float = 0.0025,
    backup: bool = True,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Process all JSON and TXT label files in directory."""
    labels_dir = labels_dir.resolve()
    if not labels_dir.exists():
        raise FileNotFoundError(f"Labels directory not found: {labels_dir}")

    json_files = sorted(labels_dir.glob("*.json"))
    txt_files = sorted([p for p in labels_dir.glob("*.txt") if p.name != "classes.txt"])

    backup_dir = labels_dir / ".backup_labels"
    if backup and not dry_run and txt_files:
        backup_dir.mkdir(parents=True, exist_ok=True)

    total_files = len(json_files) + len(txt_files)
    total_polygons = 0
    total_orig_vertices = 0
    total_simp_vertices = 0

    # Process JSON files (Labelme / X-AnyLabeling)
    for json_path in json_files:
        polys, orig_v, simp_v = simplify_json_file(
            json_path, epsilon_ratio=epsilon_ratio, backup=backup, dry_run=dry_run
        )
        total_polygons += polys
        total_orig_vertices += orig_v
        total_simp_vertices += simp_v

    # Process TXT files (YOLO)
    for txt_path in txt_files:
        if backup and not dry_run:
            shutil.copy2(txt_path, backup_dir / txt_path.name)

        new_lines, polys_cnt, orig_v, simp_v = simplify_yolo_file(txt_path, epsilon_ratio)
        total_polygons += polys_cnt
        total_orig_vertices += orig_v
        total_simp_vertices += simp_v

        if not dry_run and new_lines:
            txt_path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")

    reduction_pct = (
        ((total_orig_vertices - total_simp_vertices) / total_orig_vertices * 100.0) if total_orig_vertices > 0 else 0.0
    )

    return {
        "processed_files": total_files,
        "modified_polygons": total_polygons,
        "orig_vertices": total_orig_vertices,
        "simp_vertices": total_simp_vertices,
        "reduction_pct": reduction_pct,
    }


def print_report(stats: dict[str, Any], epsilon_ratio: float, dry_run: bool) -> None:
    """Print tabular execution report."""
    mode_str = " (DRY-RUN - Sem alterações no disco)" if dry_run else ""
    print("\n=========================================================")
    print(f"   RELATÓRIO DE SIMPLIFICAÇÃO DE POLÍGONOS YOLO/JSON{mode_str}")
    print("=========================================================")
    print(f" Tolerância (epsilon_ratio): {epsilon_ratio:.4f}")
    print(f" Total de arquivos processados: {stats['processed_files']}")
    print(f" Total de polígonos:         {stats['modified_polygons']}")
    print(f" Vértices (Antes):           {stats['orig_vertices']}")
    print(f" Vértices (Depois):          {stats['simp_vertices']}")
    print(f" Redução de ruído/vértices:  {stats['reduction_pct']:.2f}%")
    print("=========================================================\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Simplify YOLO & Labelme segmentation polygons using Douglas-Peucker algorithm."
    )
    parser.add_argument(
        "--labels-dir",
        type=Path,
        default=DEFAULT_LABELS_DIR,
        help="Directory containing label files (.json and .txt)",
    )
    parser.add_argument(
        "--epsilon-ratio",
        type=float,
        default=0.0025,
        help="Tolerance ratio relative to polygon perimeter (default: 0.0025)",
    )
    parser.add_argument(
        "--no-backup",
        dest="backup",
        action="store_false",
        help="Disable automatic backup of original files",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Calculate metrics and display report without modifying files on disk",
    )

    args = parser.parse_args()
    results = process_directory(
        args.labels_dir,
        epsilon_ratio=args.epsilon_ratio,
        backup=args.backup,
        dry_run=args.dry_run,
    )
    print_report(results, args.epsilon_ratio, args.dry_run)
